// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: message.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace SkillBridge.Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player")]
        public NPlayerInfo Player { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NCharacterInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"config_id")]
        public int ConfigId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"enity_id")]
        public int EnityId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"type")]
        public CharacterType Type { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"class")]
        public CharacterClass Class { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int mapId { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"entity")]
        public NEntity Entity { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"gold")]
        public long Gold { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<NItemInfo> Items { get; } = new global::System.Collections.Generic.List<NItemInfo>();

        [global::ProtoBuf.ProtoMember(12)]
        public NBagInfo Bag { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public byte[] Equips { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"quests")]
        public global::System.Collections.Generic.List<NQuestInfo> Quests { get; } = new global::System.Collections.Generic.List<NQuestInfo>();

        [global::ProtoBuf.ProtoMember(15, Name = @"friends")]
        public global::System.Collections.Generic.List<NFriendInfo> Friends { get; } = new global::System.Collections.Generic.List<NFriendInfo>();

        [global::ProtoBuf.ProtoMember(16, Name = @"gulid")]
        public NGulidInfo Gulid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public int Count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NBagInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Unlocked { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] Items { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NVector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public int Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public StatusType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"action")]
        public StatusAction Action { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"value")]
        public int Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StatusNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"status")]
        public global::System.Collections.Generic.List<NStatus> Status { get; } = new global::System.Collections.Generic.List<NStatus>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NEntity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public NVector3 Position { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"direction")]
        public NVector3 Direction { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"speed")]
        public int Speed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NEntitySync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event")]
        public EntityEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"entity")]
        public NEntity Entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NetMessageRequest Request { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NetMessageResponse Response { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public UserRegisterRequest userRegister { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public UserLoginRequest userLogin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public UserCreateCharacterRequest createChar { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public UserGameEnterRequest gameEnter { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public UserGameLeaveRequest gameLeave { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public MapCharacterEnterRequest mapCharacterEnter { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public MapEntitySyncRequest mapEntitySync { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public MapTeleportRequest mapTeleport { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public FirstTestRequest firstRequest { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"bagsave")]
        public BagSaveRequest Bagsave { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public ItemBuyRequest itemBuy { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public ItemEquipRequest itemEquip { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public QuestListRequest questList { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public QuestAcceptRequest questAccept { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public QuestSubmitRequest questSubmit { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public QuestAbandonRequest questAbandon { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public FriendAddRequest friendAddRequest { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public FriendAddResponse friendAddResponset { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public FriendListRequest friendList { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public FriendRemoveRequest friendRemove { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public teamInviteRequest teamInviteRequest { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public TeamInviteResponse teamInviteResponse { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public TeamInfoRequest teamInfo { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public TeamLeaveRequest teamLeave { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public GulidCreatRequest gulidCreat { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public GulidJoinRequest gulidJoinRequest { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public GulidJoinResponse gulidJoinResponse { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public GulidInfoRequest gulidInfo { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public GulidListRequest gulidList { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public GulidLeaveRequest gulidLeave { get; set; }

        [global::ProtoBuf.ProtoMember(32)]
        public GulidAdminRequest gulidAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"chat")]
        public ChatRequest Chat { get; set; }

        [global::ProtoBuf.ProtoMember(100)]
        public StatusNotify statusNotify { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public UserRegisterResponse userRegister { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public UserLoginResponse userLogin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public UserCreateCharacterResponse createChar { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public UserGameEnterResponse gameEnter { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public UserGameLeaveResponse gameLeave { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public MapCharacterEnterResponse mapCharacterEnter { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public MapCharacterLeaveResponse mapCharacterLeave { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public MapEntitySyncResponse mapEntitySync { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"bagsave")]
        public BagSaveRespose Bagsave { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public ItemBuyResponse itemBuy { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public ItemEquipRespose itemEquip { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public QuestListRespose questList { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public QuestAcceptRespose questAccept { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public QuestSubmitRespose questSubmit { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public QuestAbandonRespose questAbandon { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public FriendAddRequest friendAddRequest { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public FriendAddResponse friendAddResponset { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public FriendListResponse friendList { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public FriendRemoveResponse friendRemove { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public teamInviteRequest teamInviteRequest { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public TeamInviteResponse teamInviteResponse { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public TeamInfoResponse teamInfo { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public TeamLeaveResponse teamLeave { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public GulidCreatResponse gulidCreat { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public GulidJoinRequest gulidJoinRequest { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public GulidJoinResponse gulidJoinResponse { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public GulidInfoResponse gulidInfo { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public GulidListResponse gulidList { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public GulidLeaveResponse gulidLeave { get; set; }

        [global::ProtoBuf.ProtoMember(32)]
        public GulidAdminResponse gulidAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"chat")]
        public ChatResponse Chat { get; set; }

        [global::ProtoBuf.ProtoMember(100)]
        public StatusNotify statusNotify { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FirstTestRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"helloword")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Helloword { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserLoginRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string User { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"passward")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passward { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserLoginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"userinfo")]
        public NUserInfo Userinfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserRegisterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string User { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"passward")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Passward { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserRegisterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserCreateCharacterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"class")]
        public CharacterClass Class { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserCreateCharacterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameEnterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int characterIdx { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameEnterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public NCharacterInfo Ncharacterinfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameLeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NCharacterInfo Character { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserGameLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCharacterEnterRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCharacterEnterResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int mapId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapCharacterLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int characterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapEntitySyncRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NEntitySync entitySync { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapEntitySyncResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<NEntitySync> entitySyncs { get; } = new global::System.Collections.Generic.List<NEntitySync>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapTeleportRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int teleporterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagSaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NBagInfo BagInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagSaveRespose : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemBuyRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int shopId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int shopItemId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemBuyResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemEquipRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot")]
        public int Slot { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int itemId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool isEquip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemEquipRespose : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NQuestInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"quest_guid")]
        public int QuestGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public QuestStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"targets", IsPacked = true)]
        public int[] Targets { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public QuestListType listType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestListRespose : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"quests")]
        public global::System.Collections.Generic.List<NQuestInfo> Quests { get; } = new global::System.Collections.Generic.List<NQuestInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAcceptRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAcceptRespose : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"quest")]
        public NQuestInfo Quest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestSubmitRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestSubmitRespose : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"quest")]
        public NQuestInfo Quest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAbandonRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id")]
        public int QuestId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestAbandonRespose : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NFriendInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NCharacterInfo friendInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendAddRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"from_Id")]
        public int fromId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"to_Id")]
        public int toId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"to_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendAddResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"request")]
        public FriendAddRequest Request { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendListResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"friends")]
        public global::System.Collections.Generic.List<NFriendInfo> Friends { get; } = new global::System.Collections.Generic.List<NFriendInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendRemoveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"friend_Id")]
        public int friendId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendRemoveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"friend_Id")]
        public int friendId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NteamInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"leader_Id")]
        public int leaderId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"members")]
        public global::System.Collections.Generic.List<NCharacterInfo> Members { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class teamInviteRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"team_Id")]
        public int teamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_Id")]
        public int fromId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"from_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"to_Id")]
        public int toId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"to_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInviteResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"request")]
        public teamInviteRequest Request { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInfoRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamInfoResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"team")]
        public NteamInfo Team { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamLeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"team_Id")]
        public int teamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"character_Id")]
        public int characterId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TeamLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NGulidInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"gulid_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GulidName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"leader_id")]
        public int LeaderId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"leader_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LeaderName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"notice")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Notice { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public int memberCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"members")]
        public global::System.Collections.Generic.List<NGulidMemberInfo> Members { get; } = new global::System.Collections.Generic.List<NGulidMemberInfo>();

        [global::ProtoBuf.ProtoMember(8, Name = @"applies")]
        public global::System.Collections.Generic.List<NGulidApplyInfo> Applies { get; } = new global::System.Collections.Generic.List<NGulidApplyInfo>();

        [global::ProtoBuf.ProtoMember(9)]
        public long creatTime { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int loadmemberCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NGulidMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"character_Id")]
        public int characterId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"title")]
        public GulidTitle Title { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"characterinfo")]
        public NCharacterInfo Characterinfo { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"join_Time")]
        public long joinTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"last_Load_Time")]
        public long lastLoadTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NGulidApplyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gulid_id")]
        public int GulidId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"character_Id")]
        public int characterId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"class")]
        public int Class { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"apply_result")]
        public ApplyResult ApplyResult { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidCreatRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"gulid_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GulidName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"gulid_notice")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GulidNotice { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidCreatResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"gulid_Info")]
        public NGulidInfo gulidInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidJoinRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"apply")]
        public NGulidApplyInfo Apply { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidJoinResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"apply")]
        public NGulidApplyInfo Apply { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidInfoRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidInfoResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"gulid_info")]
        public NGulidInfo GulidInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidListResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"gulid_infos")]
        public global::System.Collections.Generic.List<NGulidInfo> GulidInfos { get; } = new global::System.Collections.Generic.List<NGulidInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidLeaveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidLeaveResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidAdminRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"command")]
        public GulidAdminCommand Command { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target")]
        public int Target { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GulidAdminResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"command")]
        public GulidAdminCommand Command { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cannel")]
        public ChatChannel Cannel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"from_id")]
        public int FromId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"from_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FromName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"to_id")]
        public int ToId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"to_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"time")]
        public double Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ChatMessage chatMessage { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public Result Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ChatMessage> localMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<ChatMessage> worldMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<ChatMessage> systemMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<ChatMessage> privateMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<ChatMessage> teamMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<ChatMessage> gulidMessages { get; } = new global::System.Collections.Generic.List<ChatMessage>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"RESULT")]
    public enum Result
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
        Failed = 1,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_TYPE")]
    public enum CharacterType
    {
        Player = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NPC")]
        Npc = 1,
        Monster = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_CLASS")]
    public enum CharacterClass
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WARRIOR")]
        Warrior = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WIZARD")]
        Wizard = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ARCHER")]
        Archer = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_STATE")]
    public enum CharacterState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IDLE")]
        Idle = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE")]
        Move = 1,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ENTITY_EVENT")]
    public enum EntityEvent
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IDLE")]
        Idle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE_FWD")]
        MoveFwd = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE_BACK")]
        MoveBack = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"JUMP")]
        Jump = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ITEM_TYPE")]
    public enum ItemType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
        Normal = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MATERIAL")]
        Material = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TASK")]
        Task = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EQUIP")]
        Equip = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"RIDE")]
        Ride = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"EQUIP_SLOT")]
    public enum EquipSlot
    {
        [global::ProtoBuf.ProtoEnum(Name = @"WEAPON")]
        Weapon = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCESSORY")]
        Accessory = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HELMET")]
        Helmet = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CHEST")]
        Chest = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SHOULDER")]
        Shoulder = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PANTS")]
        Pants = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"BOOTS")]
        Boots = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"SLOT_MAX")]
        SlotMax = 7,
    }

    [global::ProtoBuf.ProtoContract(Name = @"STATUS_ACTION")]
    public enum StatusAction
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UPDATE")]
        Update = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ADD")]
        Add = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DELETE")]
        Delete = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"STATUS_TYPE")]
    public enum StatusType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MONEY")]
        Money = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXP")]
        Exp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SKILL_POINT")]
        SkillPoint = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM")]
        Item = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"STATUS_SOURCE")]
    public enum StatusSource
    {
    }

    [global::ProtoBuf.ProtoContract(Name = @"QUEST_STATUS")]
    public enum QuestStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IN_PROGRESS")]
        InProgress = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"COMPLATED")]
        Complated = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FINISHED")]
        Finished = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
        Failed = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"QUEST_LIST_TYPE")]
    public enum QuestListType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALL")]
        All = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IN_PROGRESS")]
        InProgress = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"FINISHED")]
        Finished = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"GULID_TITLE")]
    public enum GulidTitle
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PRESIDENT")]
        President = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"VICE_PRESIDENT")]
        VicePresident = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"APPLY_RESULT")]
    public enum ApplyResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCEPT")]
        Accept = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REJECT")]
        Reject = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"GULID_ADMIN_COMMAND")]
    public enum GulidAdminCommand
    {
        [global::ProtoBuf.ProtoEnum(Name = @"KICKOUT")]
        Kickout = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PROMOTE")]
        Promote = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPAND")]
        Dispand = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TRANSFER")]
        Transfer = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"GULID_LEAVE_WAY")]
    public enum GulidLeaveWay
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SELF")]
        Self = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"KICKOUT")]
        Kickout = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPAND")]
        Dispand = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHAT_CHANNEL")]
    public enum ChatChannel
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALL")]
        All = -1,
        [global::ProtoBuf.ProtoEnum(Name = @"LOCAL")]
        Local = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WORLD")]
        World = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM")]
        System = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PRIVATE")]
        Private = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"TEAM")]
        Team = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"GULID")]
        Gulid = 32,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
